/* Content: scenarios, vocabulary, pronunciation drills, shadowing lines, phrasebook */
window.TF = window.TF || {};

TF.CATS = [
  { id: 'all', zh: '全部' },
  { id: 'transport', zh: '航廈交通' },
  { id: 'food', zh: '美食住宿' },
  { id: 'shop', zh: '購物退稅' },
  { id: 'help', zh: '緊急求助' },
];

/* Each turn: the NPC speaks `npc`; the learner's reply is matched against `re` (any).
   `better` is the polished version shown in the debrief. */
TF.SCENARIOS = [
  {
    id: 'airport', cat: 'transport', level: 'A2', em: '✈️', title: '機場報到與登機', en: 'Airport Check-in & Boarding',
    place: 'Heathrow Terminal 3, Check-in Desk 14', accent: 'en-GB', minutes: 3,
    npc: { name: 'Emma', role: '地勤櫃台人員', em: '🧑‍✈️' },
    goal: '向櫃台說明目的地、託運一件行李、選靠窗座位，並確認登機門與時間。',
    objectives: [
      { id: 'dest', zh: '說出目的地' }, { id: 'bag', zh: '說明託運行李' },
      { id: 'seat', zh: '選擇座位' }, { id: 'gate', zh: '詢問登機門／時間' },
    ],
    phrases: [
      { en: "I'm flying to Taipei, and I'd like to check in, please.", zh: '我要飛台北，想辦理報到。' },
      { en: "I have one suitcase to check in.", zh: '我有一件行李要託運。' },
      { en: "Could I have a window seat, please?", zh: '請問可以給我靠窗的座位嗎？' },
      { en: "Which gate is it, and what time does boarding start?", zh: '請問是哪個登機門？幾點開始登機？' },
    ],
    tip: '英國機場常說 "check-in desk"、"hold luggage"（託運行李）。「託運」不要說 consign，用 check in / check a bag 最自然。',
    vocab: [
      { w: 'boarding pass', ipa: '/ˈbɔːrdɪŋ pæs/', zh: '登機證', ex: 'Please have your boarding pass ready.', exzh: '請備妥您的登機證。' },
      { w: 'check in', ipa: '/tʃek ɪn/', zh: '辦理報到／託運', ex: 'I need to check in one bag.', exzh: '我需要託運一件行李。' },
      { w: 'aisle seat', ipa: '/aɪl siːt/', zh: '走道座位', ex: 'I prefer an aisle seat.', exzh: '我比較喜歡走道座位。' },
      { w: 'gate', ipa: '/ɡeɪt/', zh: '登機門', ex: 'Your gate is B12.', exzh: '您的登機門是 B12。' },
      { w: 'carry-on', ipa: '/ˈkæri ɒn/', zh: '隨身行李', ex: 'Is this carry-on small enough?', exzh: '這個隨身行李尺寸可以嗎？' },
      { w: 'overweight', ipa: '/ˌoʊvərˈweɪt/', zh: '超重', ex: 'Your bag is two kilos overweight.', exzh: '您的行李超重兩公斤。' },
    ],
    turns: [
      { npc: "Good morning! Where are you flying to today?", zh: '早安！您今天要飛往哪裡？', obj: 'dest',
        re: [/taipei|taiwan|london|new york|tokyo|flying|going|heading|to \w+/i],
        hints: ["I'm flying to Taipei.", "I'm going to Tokyo today."], better: "Good morning! I'm flying to Taipei today.", note: '先打招呼再說目的地，語氣更自然。' },
      { npc: "Lovely. Do you have any bags to check in?", zh: '好的。請問有行李要託運嗎？', obj: 'bag',
        re: [/\b(one|two|1|2|a)\b.*(bag|suitcase|luggage|case)/i, /(bag|suitcase|luggage).*(check|hold)/i, /check/i, /(only|just).*(carry|hand)/i],
        hints: ["Yes, I have one suitcase to check in.", "Just a carry-on, thanks."], better: "Yes, I have one suitcase to check in, and this carry-on bag.", note: '同時交代託運與隨身行李，櫃台不必再追問。' },
      { npc: "Would you prefer a window or an aisle seat?", zh: '您想坐靠窗還是走道座位？', obj: 'seat',
        re: [/window|aisle/i],
        hints: ["A window seat, please.", "An aisle seat, please."], better: "A window seat, please, if one is available.", note: '加上 if one is available 更有禮貌、不會顯得強求。' },
      { npc: "No problem. Here's your boarding pass. Boarding begins at 9:40 at gate B12. Anything else I can help with?", zh: '沒問題。這是您的登機證，9:40 在 B12 登機門開始登機。還有其他需要協助的嗎？', obj: 'gate',
        re: [/gate|what time|board|where|which|wait|thank/i],
        hints: ["Could you repeat the gate number, please?", "Thank you! Is gate B12 far from here?"], better: "Thank you! Could you tell me how to get to gate B12?", note: '用 Could you tell me how to… 詢問路線，比直接問 Where 更客氣。' },
    ],
    closing: "You're welcome. Have a lovely flight!",
  },
  {
    id: 'hotel', cat: 'food', level: 'B1', em: '🏨', title: '飯店辦理入住', en: 'Hotel Check-in & Requests',
    place: 'The Grand Palace Hotel, Front Desk', accent: 'en-US', minutes: 4,
    npc: { name: 'Daniel', role: '飯店櫃台', em: '🛎️' },
    goal: '報上訂房姓名、詢問早餐與 Wi-Fi、要求多一條毯子，並問清楚退房時間。',
    objectives: [
      { id: 'res', zh: '說明已訂房' }, { id: 'brk', zh: '詢問早餐／Wi-Fi' },
      { id: 'blanket', zh: '提出額外需求' }, { id: 'out', zh: '確認退房時間' },
    ],
    phrases: [
      { en: "Hi, I have a reservation under Chen.", zh: '你好，我有用陳的名字訂房。' },
      { en: "Is breakfast included, and what's the Wi-Fi password?", zh: '請問含早餐嗎？Wi-Fi 密碼是什麼？' },
      { en: "Could I get an extra blanket, please?", zh: '可以多給我一條毯子嗎？' },
      { en: "What time is check-out?", zh: '請問幾點退房？' },
    ],
    tip: '美國飯店的 "front desk" 就是櫃台；「房間升等」是 upgrade。若要求加被子，說 extra blanket 或 extra pillow。',
    vocab: [
      { w: 'reservation', ipa: '/ˌrezərˈveɪʃn/', zh: '訂房／預約', ex: 'I have a reservation for two nights.', exzh: '我訂了兩晚。' },
      { w: 'deposit', ipa: '/dɪˈpɑːzɪt/', zh: '押金', ex: 'There is a $50 deposit.', exzh: '需要 50 美元押金。' },
      { w: 'check-out', ipa: '/ˈtʃek aʊt/', zh: '退房', ex: 'Check-out is at 11 a.m.', exzh: '退房時間是上午 11 點。' },
      { w: 'amenities', ipa: '/əˈmenətiz/', zh: '設施／備品', ex: 'What amenities do you offer?', exzh: '你們提供哪些設施？' },
      { w: 'luggage storage', ipa: '/ˈlʌɡɪdʒ ˈstɔːrɪdʒ/', zh: '行李寄放', ex: 'Can I use luggage storage after check-out?', exzh: '退房後可以寄放行李嗎？' },
      { w: 'extra', ipa: '/ˈekstrə/', zh: '額外的', ex: 'I need an extra towel.', exzh: '我需要多一條毛巾。' },
    ],
    turns: [
      { npc: "Welcome to the Grand Palace! Do you have a reservation with us?", zh: '歡迎光臨！請問您有訂房嗎？', obj: 'res',
        re: [/reserv|book|name|chen|checking in|check in/i],
        hints: ["Yes, I have a reservation under Chen.", "Hi, I booked a room for two nights."], better: "Hi, I have a reservation under Chen for two nights.", note: '一次講完姓名與天數，櫃台能更快找到訂單。' },
      { npc: "Got it, Mr. Chen. Your room is 806. Is there anything you'd like to know about the hotel?", zh: '找到了。您的房間是 806。有什麼想了解的嗎？', obj: 'brk',
        re: [/breakfast|wi-?fi|internet|password|pool|gym|elevator/i],
        hints: ["Is breakfast included?", "What's the Wi-Fi password?"], better: "Is breakfast included, and could I have the Wi-Fi password, please?", note: '兩個問題併成一句，用 and could I… 銜接。' },
      { npc: "Breakfast is 7 to 10 in the lobby restaurant, and the Wi-Fi password is on your key card. Anything else?", zh: '早餐 7 點到 10 點在大廳餐廳，Wi-Fi 密碼在房卡上。還有其他需要嗎？', obj: 'blanket',
        re: [/blanket|pillow|towel|extra|another|more|iron|hair ?dryer|quiet|late/i],
        hints: ["Could I get an extra blanket, please?", "Could you send up some more towels?"], better: "Could I get an extra blanket sent up to my room, please?", note: 'sent up to my room = 送到房間，飯店情境很常用。' },
      { npc: "Of course, I'll have housekeeping bring one up right away.", zh: '沒問題，我請房務立刻送上去。', obj: 'out',
        re: [/check-?out|leave|what time|late|storage|store|luggage/i],
        hints: ["What time is check-out?", "Can I store my luggage after check-out?"], better: "Thank you! What time is check-out, and can I leave my luggage here afterwards?", note: '先道謝再追問，台灣學習者常漏掉 Thank you。' },
    ],
    closing: "Check-out is at 11 a.m., and yes, we can hold your bags. Enjoy your stay!",
  },
  {
    id: 'restaurant', cat: 'food', level: 'A2-B1', em: '🥩', title: '餐廳流暢點餐', en: 'Restaurant Dining & Custom Orders',
    place: 'The Ivy Café, Covent Garden, London', accent: 'en-GB', minutes: 4,
    npc: { name: 'Liam', role: '服務生', em: '🍽️' },
    goal: '點一份五分熟肋眼牛排、選配菜、點一杯去冰紅茶，並禮貌詢問洗手間位置。',
    objectives: [
      { id: 'main', zh: '點主餐與熟度' }, { id: 'side', zh: '選擇配菜' },
      { id: 'drink', zh: '點飲料（去冰）' }, { id: 'wc', zh: '詢問洗手間' },
    ],
    phrases: [
      { en: "Could I get the ribeye steak, medium, please?", zh: '我要肋眼牛排，五分熟。' },
      { en: "Does that come with any sides?", zh: '請問有附配菜嗎？' },
      { en: "Could I also have an iced black tea with no ice?", zh: '可以再來一杯去冰的紅茶嗎？' },
      { en: "Could you tell me where the restroom is?", zh: '請問洗手間在哪裡？' },
    ],
    tip: '牛排熟度：Rare 三分、Medium rare 四分、Medium 五分、Medium well 七分、Well done 全熟。外國菜單沒有 "half-done"。英國說 toilet / loo，美國說 restroom。',
    vocab: [
      { w: 'medium', ipa: '/ˈmiːdiəm/', zh: '五分熟', ex: 'I would like my steak medium.', exzh: '我的牛排要五分熟。' },
      { w: 'sides', ipa: '/saɪdz/', zh: '配菜', ex: 'Would you like any sides?', exzh: '需要配菜嗎？' },
      { w: 'allergic', ipa: '/əˈlɜːrdʒɪk/', zh: '過敏的', ex: "I'm allergic to peanuts.", exzh: '我對花生過敏。' },
      { w: 'the bill', ipa: '/ðə bɪl/', zh: '帳單（英）', ex: 'Could we have the bill, please?', exzh: '請給我們帳單。' },
      { w: 'tip', ipa: '/tɪp/', zh: '小費', ex: 'Is service included, or should I tip?', exzh: '含服務費嗎？還是我要給小費？' },
      { w: 'split the bill', ipa: '/splɪt ðə bɪl/', zh: '分開結帳', ex: 'Can we split the bill?', exzh: '我們可以分開結帳嗎？' },
    ],
    turns: [
      { npc: "Good evening! Welcome to The Ivy. Are you ready to order?", zh: '晚安！歡迎光臨。準備好點餐了嗎？', obj: 'main',
        re: [/steak|ribeye|rib-eye|burger|salmon|pasta|fish|chicken|medium|rare|well/i],
        hints: ["Could I get the ribeye steak, medium, please?", "I'd like the grilled salmon, please."], better: "Hi! Could I get the ribeye steak, medium, please?", note: 'Could I get… 比 I want… 禮貌，I want 在英語裡聽起來很直接。' },
      { npc: "Excellent choice! Would you like any sides with that — fries, mash, or a side salad?", zh: '很棒的選擇！想搭配什麼配菜？薯條、馬鈴薯泥還是沙拉？', obj: 'side',
        re: [/fries|chips|mash|salad|veg|potato|rice|bread|side/i],
        hints: ["Fries, please.", "Could I have a side salad instead of fries?"], better: "Fries, please, and could I swap the sauce for pepper sauce?", note: '想換醬料可用 Could I swap… for…。' },
      { npc: "Perfect. And to drink?", zh: '好的。飲料要點什麼？', obj: 'drink',
        re: [/tea|water|coke|cola|juice|beer|wine|coffee|lemonade|drink|ice/i],
        hints: ["Could I have an iced black tea with no ice?", "Just a glass of water, please."], better: "Could I have an iced tea, but with no ice, please?", note: '"no ice" 可以直接說；也可以說 without ice。' },
      { npc: "Coming right up. Is there anything else I can get for you?", zh: '馬上來。還需要什麼嗎？', obj: 'wc',
        re: [/restroom|toilet|loo|bathroom|washroom|where/i],
        hints: ["Could you tell me where the restroom is?", "Where is the toilet, please?"], better: "Yes, could you tell me where the restroom is, please?", note: '問洗手間用 Could you tell me where…，比直接 Where is 更客氣。' },
    ],
    closing: "Of course — it's just past the bar on your left. Your steak will be out shortly!",
  },
  {
    id: 'directions', cat: 'transport', level: 'A2', em: '🧭', title: '街道問路與交通', en: 'Asking Directions & Subway Transit',
    place: 'Times Square, New York', accent: 'en-US', minutes: 3,
    npc: { name: 'Sarah', role: '路人', em: '🧍‍♀️' },
    goal: '向路人問地鐵站位置，確認要搭哪條線、走路要多久。',
    objectives: [
      { id: 'ask', zh: '問地鐵站位置' }, { id: 'line', zh: '確認搭乘路線' }, { id: 'time', zh: '詢問步行時間' },
    ],
    phrases: [
      { en: "Excuse me, how do I get to the subway station?", zh: '不好意思，請問地鐵站怎麼走？' },
      { en: "Which line should I take to get to Central Park?", zh: '要去中央公園該搭哪一線？' },
      { en: "How long does it take to walk there?", zh: '走路過去要多久？' },
      { en: "Could you say that again, a little slower, please?", zh: '可以請你再說一次，慢一點嗎？' },
    ],
    tip: '在美國，subway 是地鐵（英國說 the Tube 或 underground）。聽不懂時別只說 "What?"，改說 Could you say that again?',
    vocab: [
      { w: 'subway', ipa: '/ˈsʌbweɪ/', zh: '地鐵（美）', ex: 'The subway is faster than a taxi.', exzh: '地鐵比計程車快。' },
      { w: 'transfer', ipa: '/trænsˈfɜːr/', zh: '轉乘', ex: 'You need to transfer at 42nd Street.', exzh: '你要在 42 街轉乘。' },
      { w: 'platform', ipa: '/ˈplætfɔːrm/', zh: '月台', ex: 'Which platform is it?', exzh: '是哪個月台？' },
      { w: 'block', ipa: '/blɑːk/', zh: '街區', ex: 'Walk two blocks and turn left.', exzh: '走兩個街區後左轉。' },
      { w: 'turn right', ipa: '/tɜːrn raɪt/', zh: '右轉', ex: 'Turn right at the corner.', exzh: '在轉角右轉。' },
      { w: 'straight ahead', ipa: '/streɪt əˈhed/', zh: '直走', ex: 'Go straight ahead for five minutes.', exzh: '直走五分鐘。' },
    ],
    turns: [
      { npc: "Hi there! You look a little lost. Can I help you?", zh: '嗨！你看起來有點迷路，需要幫忙嗎？', obj: 'ask',
        re: [/subway|station|metro|train|how (do|can) i get|where/i],
        hints: ["Yes, how do I get to the subway station?", "Excuse me, where is the nearest subway station?"], better: "Yes, please! How do I get to the nearest subway station?", note: '回應幫忙時先說 Yes, please，再提問。' },
      { npc: "Sure. Walk straight for two blocks, then turn right. You'll see the station on your left.", zh: '當然。直走兩個街區再右轉，車站會在你左手邊。', obj: 'line',
        re: [/line|which|train|take|central park|uptown|downtown|transfer/i],
        hints: ["Which line should I take to get to Central Park?", "Do I need to transfer?"], better: "Thanks! Which line should I take to get to Central Park?", note: '問完先道謝，再問下一個問題。' },
      { npc: "Take the A or C line uptown. It's about six stops.", zh: '搭 A 或 C 線往北，大約六站。', obj: 'time',
        re: [/how long|minutes|far|walk|take|time/i],
        hints: ["How long does it take to walk there?", "Is it far from here?"], better: "Great, thank you. How long does it take to walk to the station?", note: 'How long does it take… 是問「要花多久」的萬用句型。' },
    ],
    closing: "About five minutes. You can't miss it. Have a great day!",
  },
  {
    id: 'shopping', cat: 'shop', level: 'B1', em: '🛍️', title: '購物與退稅', en: 'Shopping, Tax Refund & Discounts',
    place: 'Selfridges, Oxford Street, London', accent: 'en-GB', minutes: 4,
    npc: { name: 'Olivia', role: '店員', em: '🛒' },
    goal: '詢問尺寸並試穿、問折扣，最後詢問如何辦理退稅。',
    objectives: [
      { id: 'size', zh: '詢問尺寸／試穿' }, { id: 'disc', zh: '詢問折扣' }, { id: 'tax', zh: '詢問退稅' },
    ],
    phrases: [
      { en: "Do you have this in a medium? Can I try it on?", zh: '這件有 M 號嗎？我可以試穿嗎？' },
      { en: "Is there any discount on this item?", zh: '這件有折扣嗎？' },
      { en: "How do I get a tax refund?", zh: '要怎麼辦理退稅？' },
      { en: "Can I pay by card?", zh: '可以刷卡嗎？' },
    ],
    tip: '英國退稅叫 VAT refund（Tax-Free Shopping），店員會給你一張表單，離境時到機場櫃台蓋章。試穿室是 fitting room。',
    vocab: [
      { w: 'fitting room', ipa: '/ˈfɪtɪŋ ruːm/', zh: '試衣間', ex: 'Where is the fitting room?', exzh: '試衣間在哪裡？' },
      { w: 'discount', ipa: '/ˈdɪskaʊnt/', zh: '折扣', ex: 'Is there a student discount?', exzh: '有學生折扣嗎？' },
      { w: 'refund', ipa: '/ˈriːfʌnd/', zh: '退款／退稅', ex: 'I would like a refund.', exzh: '我想退款。' },
      { w: 'receipt', ipa: '/rɪˈsiːt/', zh: '收據', ex: 'Please keep your receipt.', exzh: '請保留收據。' },
      { w: 'in stock', ipa: '/ɪn stɑːk/', zh: '有現貨', ex: 'Is this size in stock?', exzh: '這個尺寸有現貨嗎？' },
      { w: 'passport', ipa: '/ˈpæspɔːrt/', zh: '護照', ex: 'I need your passport for the refund.', exzh: '退稅需要您的護照。' },
    ],
    turns: [
      { npc: "Hello! Let me know if you need any help with sizes.", zh: '您好！需要尺寸方面的協助請告訴我。', obj: 'size',
        re: [/size|medium|small|large|try|fitting|have this|have it/i],
        hints: ["Do you have this in a medium?", "Can I try this on, please?"], better: "Hi! Do you have this jacket in a medium, and could I try it on?", note: '一句同時問尺寸與試穿，節省來回。' },
      { npc: "Yes, we do. The fitting room is just there. It's £120 today.", zh: '有的。試衣間就在那邊。今天售價 120 英鎊。', obj: 'disc',
        re: [/discount|sale|cheaper|offer|deal|price|off|student/i],
        hints: ["Is there any discount on this item?", "Is it on sale?"], better: "It fits well! Is there any discount on this item?", note: 'Is there any discount… 比 Can you make it cheaper 更得體。' },
      { npc: "I can take 10% off since it's last season's. Will that be all?", zh: '因為是上一季款式，我可以幫您打九折。這樣就好嗎？', obj: 'tax',
        re: [/tax|refund|vat|tourist|tax-?free|form|receipt/i],
        hints: ["How do I get a tax refund?", "Do you offer tax-free shopping for tourists?"], better: "That sounds good. How do I get a tax refund as a tourist?", note: 'as a tourist 讓店員立即知道你要辦退稅。' },
    ],
    closing: "I'll give you the VAT form. Just show it with your passport at the airport. Thank you!",
  },
  {
    id: 'emergency', cat: 'help', level: 'B1', em: '🚑', title: '藥局與緊急求助', en: 'Pharmacy & Emergency Help',
    place: 'Boots Pharmacy, London', accent: 'en-GB', minutes: 3,
    npc: { name: 'Priya', role: '藥師', em: '👩‍⚕️' },
    goal: '說明症狀、提到過敏，並詢問用法與用量。',
    objectives: [
      { id: 'sym', zh: '描述症狀' }, { id: 'allergy', zh: '說明過敏／用藥史' }, { id: 'dose', zh: '詢問用法' },
    ],
    phrases: [
      { en: "I have a headache and a sore throat.", zh: '我頭痛而且喉嚨痛。' },
      { en: "I'm allergic to penicillin.", zh: '我對盤尼西林過敏。' },
      { en: "How many times a day should I take it?", zh: '一天要吃幾次？' },
      { en: "I need help. Please call an ambulance.", zh: '我需要協助，請叫救護車。' },
    ],
    tip: '真正緊急情況（美國）撥 911、（英國）撥 999、（歐盟）112。說 "I need an ambulance" 並報出地點即可。',
    vocab: [
      { w: 'headache', ipa: '/ˈhedeɪk/', zh: '頭痛', ex: 'I have a terrible headache.', exzh: '我頭痛得很厲害。' },
      { w: 'prescription', ipa: '/prɪˈskrɪpʃn/', zh: '處方箋', ex: 'Do I need a prescription?', exzh: '需要處方箋嗎？' },
      { w: 'allergic', ipa: '/əˈlɜːrdʒɪk/', zh: '過敏的', ex: "I'm allergic to shellfish.", exzh: '我對甲殼類過敏。' },
      { w: 'ambulance', ipa: '/ˈæmbjələns/', zh: '救護車', ex: 'Please call an ambulance.', exzh: '請叫救護車。' },
      { w: 'dosage', ipa: '/ˈdoʊsɪdʒ/', zh: '劑量', ex: 'What is the recommended dosage?', exzh: '建議劑量是多少？' },
      { w: 'symptoms', ipa: '/ˈsɪmptəmz/', zh: '症狀', ex: 'What are your symptoms?', exzh: '你有哪些症狀？' },
    ],
    turns: [
      { npc: "Hello, how can I help you today?", zh: '您好，今天需要什麼協助？', obj: 'sym',
        re: [/headache|fever|cough|sore|throat|pain|hurt|stomach|cold|flu|sick|feel/i],
        hints: ["I have a headache and a sore throat.", "I have a stomachache since last night."], better: "Hi, I've had a headache and a sore throat since yesterday.", note: 'since yesterday 能告訴藥師症狀持續多久。' },
      { npc: "I see. Are you allergic to any medication, or are you taking anything at the moment?", zh: '了解。您對任何藥物過敏嗎？目前有在服用什麼藥嗎？', obj: 'allergy',
        re: [/allerg|penicillin|nothing|no\b|not taking|don't|do not|aspirin/i],
        hints: ["I'm allergic to penicillin.", "No allergies, and I'm not taking anything."], better: "I'm allergic to penicillin, and I'm not taking anything else.", note: '過敏要說 allergic to + 藥名，這句在國外非常重要。' },
      { npc: "Then these tablets should be fine. They're over the counter.", zh: '那這些藥片應該沒問題，是不需處方的成藥。', obj: 'dose',
        re: [/how (many|often|much)|times|day|dose|dosage|take it|with food|before|after/i],
        hints: ["How many times a day should I take it?", "Should I take it with food?"], better: "Thank you. How many times a day should I take it, and should I take it with food?", note: 'with food = 飯後服用，是最常見的用藥問題。' },
    ],
    closing: "Two tablets, three times a day, after meals. Feel better soon!",
  },
  {
    id: 'sfo', cat: 'transport', level: 'B2', em: '🛫', title: '轉機延誤改簽', en: 'Missed Connection & Rebooking',
    place: 'SFO Terminal 2, Transfer Desk B', accent: 'en-US', minutes: 5,
    npc: { name: 'David', role: '轉機櫃台地勤', em: '🧑‍💼' },
    goal: '說明前段航班延誤，要求改簽最早的班機，並詢問餐券與行李轉運。',
    objectives: [
      { id: 'delay', zh: '說明航班延誤' }, { id: 'rebook', zh: '要求改簽' },
      { id: 'voucher', zh: '詢問餐券' }, { id: 'luggage', zh: '確認行李' },
    ],
    phrases: [
      { en: "My connecting flight was delayed, and I might miss my connection.", zh: '我的前段班機延誤，可能趕不上轉機。' },
      { en: "Could you please check if there are any seats on the next flight to New York?", zh: '能請你查一下下一班飛紐約的班機還有位子嗎？' },
      { en: "Is there a meal voucher available for the delay?", zh: '這次延誤有提供餐券嗎？' },
      { en: "Will my luggage be transferred automatically?", zh: '我的行李會自動轉運嗎？' },
    ],
    tip: '談判心法：溫和但堅定。用 Could you please check if… 比直接命令更能引發同理心；遇到延誤可明確詢問 compensation（補償）。',
    vocab: [
      { w: 'rebook', ipa: '/ˌriːˈbʊk/', zh: '改簽', ex: 'The agent helped me rebook my flight.', exzh: '地勤協助我改簽。' },
      { w: 'layover', ipa: '/ˈleɪoʊvər/', zh: '中途停留', ex: 'I have a three-hour layover.', exzh: '我有三小時轉機等待時間。' },
      { w: 'delayed', ipa: '/dɪˈleɪd/', zh: '延誤', ex: 'Our flight was delayed by fifty minutes.', exzh: '我們的班機延誤了五十分鐘。' },
      { w: 'voucher', ipa: '/ˈvaʊtʃər/', zh: '餐券／禮券', ex: 'You are eligible for a meal voucher.', exzh: '您可領取餐券。' },
      { w: 'connection', ipa: '/kəˈnekʃn/', zh: '轉機銜接', ex: "I'm going to miss my connection.", exzh: '我趕不上轉機了。' },
      { w: 'baggage claim', ipa: '/ˈbæɡɪdʒ kleɪm/', zh: '行李提領處', ex: 'Where is the baggage claim?', exzh: '行李提領處在哪裡？' },
    ],
    turns: [
      { npc: "Hello sir, how can I assist you today? I see you just arrived on flight CX-882.", zh: '先生您好，有什麼我能協助的嗎？我看到您剛搭 CX-882 抵達。', obj: 'delay',
        re: [/delay|late|miss|connect|only .*minutes|40/i],
        hints: ["My flight was delayed, and I only have forty minutes left.", "I might miss my connecting flight."], better: "Hi, my connecting flight was delayed, and I might miss my connection.", note: '用 might 表示可能性，比 will 更準確且不誇張。' },
      { npc: "I understand. AA-1940 is boarding soon, so it will be very tight. Would you like me to look at other options?", zh: '我理解。AA-1940 即將登機，時間很緊。要我幫您看其他選擇嗎？', obj: 'rebook',
        re: [/rebook|re-book|next|another|other flight|available|seat|change/i],
        hints: ["Yes, could you rebook me on the next available flight?", "Could you check if there are any seats on the next flight to New York?"], better: "Yes, please. Could you check if there are any seats on the next flight to New York?", note: 'Could you check if… 是最常見的禮貌請求句型。' },
      { npc: "There's a direct flight, AA-2088, at 3:15 PM. I've rebooked you on that one. Anything else?", zh: '有一班 3:15 PM 的直飛班機 AA-2088，我已幫您改簽。還有其他需要嗎？', obj: 'voucher',
        re: [/voucher|meal|food|lunch|compensat|hotel|lounge/i],
        hints: ["Is there a meal voucher available for the delay?", "Is there any compensation for the delay?"], better: "Thank you so much. Is there a meal voucher available, since I'll be waiting for several hours?", note: '補上理由（since…）能讓請求更站得住腳。' },
      { npc: "Yes, I'll print a $25 voucher for you. Is there anything else you'd like to confirm?", zh: '有的，我給您一張 25 美元餐券。還有想確認的事嗎？', obj: 'luggage',
        re: [/luggage|baggage|bag|suitcase|transfer|checked/i],
        hints: ["Will my luggage be transferred automatically?", "What about my checked bag?"], better: "Yes, one last thing. Will my checked luggage be transferred to the new flight automatically?", note: 'one last thing 是自然的收尾語，表示這是最後一個問題。' },
    ],
    closing: "Yes, it will be moved automatically. You're all set — gate B24, seat 14C. Safe travels!",
  },
  {
    id: 'coffee', cat: 'food', level: 'B1', em: '☕', title: '咖啡廳客製點餐', en: 'Coffee Shop Custom Order',
    place: 'Camden Coffee, London', accent: 'en-GB', minutes: 3,
    npc: { name: 'Sophia', role: '咖啡師', em: '🧋' },
    goal: '點一杯燕麥奶冰拿鐵、要求少糖，並加點一份可頌。',
    objectives: [
      { id: 'drink', zh: '點飲料與奶種' }, { id: 'custom', zh: '客製甜度' }, { id: 'food', zh: '加點餐點' },
    ],
    phrases: [
      { en: "Hi! I'd like an iced oat milk latte, please.", zh: '嗨！我要一杯燕麥奶冰拿鐵。' },
      { en: "Could you make it less sweet?", zh: '可以做得不要那麼甜嗎？' },
      { en: "I'll take an almond croissant, please.", zh: '我要一個杏仁可頌。' },
      { en: "Is that for here or to go?", zh: '內用還是外帶？（店員常問）' },
    ],
    tip: '"For here or to go?"（美）／"Eat in or take away?"（英）是內用／外帶。甜度可說 half sweet、less syrup、no sugar。',
    vocab: [
      { w: 'oat milk', ipa: '/oʊt mɪlk/', zh: '燕麥奶', ex: 'Can I get that with oat milk?', exzh: '可以換成燕麥奶嗎？' },
      { w: 'latte', ipa: '/ˈlɑːteɪ/', zh: '拿鐵', ex: 'One iced latte, please.', exzh: '請給我一杯冰拿鐵。' },
      { w: 'syrup', ipa: '/ˈsɪrəp/', zh: '糖漿', ex: 'Half syrup, please.', exzh: '糖漿減半。' },
      { w: 'croissant', ipa: '/krwɑːˈsɒ̃/', zh: '可頌', ex: 'The croissants are fresh out of the oven.', exzh: '可頌剛出爐。' },
      { w: 'to go', ipa: '/tə ɡoʊ/', zh: '外帶', ex: 'Can I get that to go?', exzh: '可以外帶嗎？' },
      { w: 'gluten-free', ipa: '/ˈɡluːtn friː/', zh: '無麩質', ex: 'Is this scone gluten-free?', exzh: '這個司康是無麩質的嗎？' },
    ],
    turns: [
      { npc: "Good morning! Welcome to Camden Coffee. What can I get started for you today?", zh: '早安！歡迎光臨。今天想先點什麼？', obj: 'drink',
        re: [/latte|coffee|americano|flat white|cappuccino|mocha|tea|oat|milk|iced|hot/i],
        hints: ["I'd like an iced oat milk latte, please.", "Could I have a hot flat white?"], better: "Hi! I'd like an iced oat milk latte, please.", note: '冰/熱 + 奶種 + 飲品，順序是 iced oat milk latte。' },
      { npc: "Certainly! Would you like any syrup in that?", zh: '沒問題！需要加糖漿嗎？', obj: 'custom',
        re: [/less|half|no (sugar|syrup)|without|sweet|sugar|syrup|extra|light/i],
        hints: ["Could you make it less sweet?", "Just half syrup, please."], better: "Could you make it less sweet? Half syrup would be great.", note: 'less sweet / half syrup 都是道地說法。' },
      { npc: "One iced oat latte with half syrup. Anything to eat with that? Our croissants just came out of the oven.", zh: '一杯燕麥冰拿鐵，糖漿減半。要配點什麼嗎？可頌剛出爐喔。', obj: 'food',
        re: [/croissant|scone|muffin|cake|cookie|sandwich|pastry|pastries|vegan|gluten|nothing|that's all|that is all/i],
        hints: ["Sure, I'll take an almond croissant.", "Is the matcha scone gluten-free?"], better: "Sure, I'll take an almond croissant. And that's all for today, thanks!", note: "That's all for today 是結束點餐的自然收尾。" },
    ],
    closing: "Lovely! That'll be £7.20. We'll call your name when it's ready.",
  },
];

/* Pronunciation drills: Taiwanese-learner trouble spots. `focus` maps key word -> IPA. */
TF.DRILLS = [
  { id: 'th', sym: '/θ/', title: 'th 咬舌音', sub: '別唸成「ㄙ」', key: 'th',
    tip: '舌尖輕放在上下齒之間，放鬆吐氣，讓氣流從齒縫摩擦而出。不要唸成注音的「ㄙ」或「ㄊ」。',
    items: [
      { text: 'I think three thousand people threw red roses.', zh: '我想有三千人丟了紅玫瑰。', focus: { think: '/θɪŋk/', three: '/θriː/', thousand: '/ˈθaʊznd/', threw: '/θruː/' } },
      { text: 'Thank you for the thirty-third birthday gift.', zh: '謝謝你的三十三歲生日禮物。', focus: { thank: '/θæŋk/', thirty: '/ˈθɜːrti/', third: '/θɜːrd/' } },
      { text: 'Both of my brothers think this is worth it.', zh: '我兩個兄弟都覺得這很值得。', focus: { both: '/boʊθ/', think: '/θɪŋk/', worth: '/wɜːrθ/' } },
    ] },
  { id: 'rl', sym: '/r/ · /l/', title: 'R / L 舌位', sub: 'Right vs Light', key: 'rl',
    tip: '/r/ 舌尖不碰上顎，舌頭向後捲、嘴唇微圓；/l/ 舌尖頂住上齒齦。可先用 right / light 對比練習。',
    items: [
      { text: 'The light is right on the red railway.', zh: '光線剛好照在紅色鐵路上。', focus: { light: '/laɪt/', right: '/raɪt/', red: '/red/', railway: '/ˈreɪlweɪ/' } },
      { text: 'Please read the long letter really carefully.', zh: '請非常仔細地閱讀這封長信。', focus: { read: '/riːd/', long: '/lɔːŋ/', letter: '/ˈletər/', really: '/ˈriːəli/' } },
      { text: 'I would like a large glass of red wine.', zh: '我想要一大杯紅酒。', focus: { like: '/laɪk/', large: '/lɑːrdʒ/', glass: '/ɡlæs/', red: '/red/' } },
    ] },
  { id: 'vb', sym: '/v/ · /b/', title: 'V / B 唇齒音', sub: 'very ≠ berry', key: 'vb',
    tip: '/v/ 上齒輕咬下唇，讓氣流振動摩擦；/b/ 是雙唇爆破。台灣人常把 /v/ 唸成 /b/。',
    items: [
      { text: 'The very best vegetables are available in the village.', zh: '村子裡可以買到最好的蔬菜。', focus: { very: '/ˈveri/', vegetables: '/ˈvedʒtəbəlz/', available: '/əˈveɪləbl/', village: '/ˈvɪlɪdʒ/' } },
      { text: 'I have a visa for the voyage in November.', zh: '我有十一月航行的簽證。', focus: { have: '/hæv/', visa: '/ˈviːzə/', voyage: '/ˈvɔɪɪdʒ/', november: '/noʊˈvembər/' } },
    ] },
  { id: 'ae', sym: '/æ/', title: 'æ 短母音', sub: 'bad / bed', key: 'ae',
    tip: '嘴巴張大、下巴往下放，舌位平低，比中文「ㄝ」更開。對比 bad /bæd/ 與 bed /bed/。',
    items: [
      { text: 'The black cat sat on the flat map.', zh: '黑貓坐在平坦的地圖上。', focus: { black: '/blæk/', cat: '/kæt/', sat: '/sæt/', flat: '/flæt/', map: '/mæp/' } },
      { text: 'Hand me that bag and have a snack.', zh: '把那個包包遞給我，吃點點心吧。', focus: { hand: '/hænd/', that: '/ðæt/', bag: '/bæɡ/', snack: '/snæk/' } },
    ] },
  { id: 'ng', sym: '/ŋ/', title: 'ŋ 鼻尾音', sub: 'sing 的結尾', key: 'ng',
    tip: '舌根頂住軟顎、氣流由鼻腔出來，結尾不要多出一個 /g/ 或唸成 /n/。',
    items: [
      { text: 'I am singing a long song this evening.', zh: '今晚我正在唱一首長歌。', focus: { singing: '/ˈsɪŋɪŋ/', long: '/lɔːŋ/', song: '/sɔːŋ/', evening: '/ˈiːvnɪŋ/' } },
      { text: 'Nothing is wrong with bringing something.', zh: '帶點東西來沒有什麼不對。', focus: { nothing: '/ˈnʌθɪŋ/', wrong: '/rɔːŋ/', bringing: '/ˈbrɪŋɪŋ/', something: '/ˈsʌmθɪŋ/' } },
    ] },
  { id: 'sh', sym: '/ʃ/ · /tʃ/', title: 'sh / ch 氣息音', sub: 'ship vs chip', key: 'sh',
    tip: '/ʃ/ 嘴唇微噘、氣流持續摩擦；/tʃ/ 先擋住氣流再釋放。注意 sheep /ʃiːp/ 與 cheap /tʃiːp/ 的差別。',
    items: [
      { text: 'She sells fresh cheap cherries at the shop.', zh: '她在店裡賣新鮮便宜的櫻桃。', focus: { she: '/ʃiː/', fresh: '/freʃ/', cheap: '/tʃiːp/', cherries: '/ˈtʃeriz/', shop: '/ʃɑːp/' } },
      { text: 'Choose a child-sized chair to sit in the kitchen.', zh: '選一張兒童尺寸的椅子坐在廚房。', focus: { choose: '/tʃuːz/', child: '/tʃaɪld/', chair: '/tʃer/', kitchen: '/ˈkɪtʃɪn/' } },
    ] },
];

/* Shadowing: original practice lines (self-authored, native-speed rhythm) */
TF.SHADOW = [
  { text: "Confidence isn't about being loud; it's about being comfortable with silence.", zh: '自信並不在於大聲，而是能從容面對沉默。', note: '重音落在 confidence、loud、comfortable、silence；"about being" 連音成 /əˈbaʊ·tbiːɪŋ/。', link: 'about being' },
  { text: "The best way to learn a language is to use it every single day.", zh: '學語言最好的方法，就是每天都使用它。', note: '"every single day" 三個詞各自重讀，節奏平均；"to use it" 輕讀。', link: 'use it' },
  { text: "I'd rather make a mistake than stay quiet and never improve.", zh: '我寧可犯錯，也不要沉默而毫無進步。', note: "I'd rather 縮讀成 /aɪd ˈræðər/；mistake 重音在第二音節。", link: "I'd rather" },
  { text: "Could you tell me where I can find a good place to eat nearby?", zh: '請問你知道附近哪裡有好吃的地方嗎？', note: "Could you 常連成 /ˈkʊdʒu/；句尾 nearby 音調下降。", link: 'Could you' },
  { text: "If we leave now, we can still catch the last train home.", zh: '如果現在出發，我們還趕得上最後一班回家的車。', note: '"catch the" 中 /tʃ/ 與 /ð/ 銜接要快；"last train" 的 t 輕化。', link: 'catch the' },
  { text: "What matters most is not how fast you speak, but how clearly.", zh: '最重要的不是你講得多快，而是講得多清楚。', note: 'not…but… 對比結構：fast 與 clearly 要明顯重讀。', link: 'but how' },
  { text: "I've been practicing every morning, and I can really feel the difference.", zh: '我每天早上都在練習，真的能感受到差別。', note: "I've been 縮讀成 /aɪv bɪn/；really 的 r 與 l 要區分。", link: "I've been" },
  { text: "Thank you so much for waiting; I really appreciate your patience.", zh: '非常感謝您的等候，我很感激您的耐心。', note: 'appreciate 重音在第二音節 /əˈpriːʃieɪt/；th 與 sh 都要到位。', link: 'Thank you' },
];

TF.PB_CATS = [
  { id: 'all', zh: '全部' }, { id: 'dining', zh: '餐廳點餐' }, { id: 'airport', zh: '機場航廈' },
  { id: 'hotel', zh: '飯店住宿' }, { id: 'dir', zh: '交通問路' }, { id: 'shop', zh: '購物退稅' }, { id: 'sos', zh: '緊急求助' },
];
TF.PHRASEBOOK = [
  { id: 'p1', c: 'dining', en: 'Could I have the check, please? Can we split the bill?', zh: '可以給我帳單嗎？我們可以分開結帳嗎？', note: '🇬🇧 英國用 the bill；🇺🇸 美國用 the check。', pri: 1 },
  { id: 'p2', c: 'dining', en: "I'm allergic to peanuts. Does this dish contain any nuts?", zh: '我對花生過敏。這道菜有任何堅果嗎？', note: '⚠️ 飲食過敏必備救命句，點餐前先講。', pri: 1 },
  { id: 'p3', c: 'dining', en: 'Excuse me, could we get some tap water for the table?', zh: '不好意思，可以給我們這桌一些自來水嗎？', note: 'tap water 通常免費；sparkling / still water 需額外收費。' },
  { id: 'p4', c: 'dining', en: 'Everything was delicious, compliments to the chef!', zh: '每道菜都很美味，請向主廚致意！', note: '用餐後的禮貌回饋。' },
  { id: 'p5', c: 'dining', en: 'Could I see the menu, please? Do you have a vegetarian option?', zh: '可以給我菜單嗎？有素食選擇嗎？', note: '素食：vegetarian；純素：vegan。' },
  { id: 'p6', c: 'airport', en: 'Where is the check-in counter for this airline?', zh: '這家航空的報到櫃台在哪裡？', note: '' },
  { id: 'p7', c: 'airport', en: 'Could I have a window seat, please?', zh: '可以給我靠窗的座位嗎？', note: 'aisle = 走道；window = 靠窗。', pri: 1 },
  { id: 'p8', c: 'airport', en: 'My flight was delayed. Can I be rebooked on the next flight?', zh: '我的班機延誤了，可以改簽下一班嗎？', note: '轉機延誤時最重要的一句。', pri: 1 },
  { id: 'p9', c: 'airport', en: 'Excuse me, which gate does this flight depart from?', zh: '請問這班飛機從哪個登機門出發？', note: '' },
  { id: 'p10', c: 'airport', en: 'I have nothing to declare.', zh: '我沒有需要申報的物品。', note: '海關最常聽到的一句。' },
  { id: 'p11', c: 'hotel', en: 'Hi, I have a reservation under Chen.', zh: '你好，我有用陳的名字訂房。', note: '' },
  { id: 'p12', c: 'hotel', en: 'Could I get an extra blanket and two more towels?', zh: '可以多給我一條毯子跟兩條毛巾嗎？', note: '' },
  { id: 'p13', c: 'hotel', en: 'What time is check-out? Can I leave my luggage here afterwards?', zh: '幾點退房？退房後可以寄放行李嗎？', note: '' },
  { id: 'p14', c: 'hotel', en: "The air conditioning isn't working. Could someone take a look?", zh: '冷氣壞了，可以請人來看看嗎？', note: '' },
  { id: 'p15', c: 'dir', en: 'Excuse me, how do I get to the subway station?', zh: '不好意思，請問地鐵站怎麼走？', note: '英國：the Tube / underground。', pri: 1 },
  { id: 'p16', c: 'dir', en: 'Is it within walking distance, or should I take a taxi?', zh: '走路到得了嗎？還是該搭計程車？', note: '' },
  { id: 'p17', c: 'dir', en: 'Could you say that again, a little slower, please?', zh: '可以請你再說一次、慢一點嗎？', note: '聽不懂時的救命句。', pri: 1 },
  { id: 'p18', c: 'dir', en: 'Does this bus go to the city centre?', zh: '這班公車會到市中心嗎？', note: '美式拼法 center。' },
  { id: 'p19', c: 'shop', en: 'Do you have this in a medium? Can I try it on?', zh: '這件有 M 號嗎？可以試穿嗎？', note: '' },
  { id: 'p20', c: 'shop', en: 'How do I get a tax refund as a tourist?', zh: '觀光客要怎麼辦理退稅？', note: '離境前記得在機場蓋章。' },
  { id: 'p21', c: 'shop', en: "That's a bit over my budget. Is there any discount?", zh: '有點超出預算，有折扣嗎？', note: '比 "Too expensive" 委婉。' },
  { id: 'p22', c: 'shop', en: 'Can I pay by card, or is it cash only?', zh: '可以刷卡嗎？還是只收現金？', note: '' },
  { id: 'p23', c: 'sos', en: 'I need help. Please call an ambulance.', zh: '我需要幫助，請叫救護車。', note: '美國 911、英國 999、歐盟 112。', pri: 1 },
  { id: 'p24', c: 'sos', en: "I've lost my passport. Where is the nearest police station?", zh: '我弄丟護照了，最近的警察局在哪裡？', note: '', pri: 1 },
  { id: 'p25', c: 'sos', en: 'I have a headache and a fever. Do you have anything for it?', zh: '我頭痛又發燒，有什麼藥可以吃嗎？', note: '' },
  { id: 'p26', c: 'sos', en: "I think I'm lost. Could you help me find this address?", zh: '我好像迷路了，可以幫我找這個地址嗎？', note: '' },
];

/* Free-talk topics */
TF.TOPICS = [
  { id: 'intro', zh: '自我介紹', q: "Hi! I'm your English coach. Let's start easy — could you introduce yourself? Tell me your name and what you do.", follow: ['What do you enjoy most about your job or studies?', 'What do you usually do on weekends?', 'Why do you want to improve your English?'] },
  { id: 'travel', zh: '旅行經驗', q: "Let's talk about travel. What's the most memorable place you've ever visited, and why?", follow: ['Who did you go with?', 'What was the best thing you ate there?', 'Where would you like to go next?'] },
  { id: 'food', zh: '美食', q: "What's your favourite food in Taiwan, and how would you describe it to someone who has never tried it?", follow: ['How is it usually cooked?', 'Is there any food you really dislike?', 'Which restaurant would you recommend to a visitor?'] },
  { id: 'work', zh: '工作／學習', q: "Tell me about a typical day at work or school. What do you do from morning to evening?", follow: ['What is the most challenging part of your day?', 'How do you relax after work?', 'What skill would you like to learn this year?'] },
];

/* Common Taiwanese-learner errors detected in free talk */
TF.GRAMMAR = [
  { re: /\bi very (like|love|want|enjoy)\b/i, say: 'I really $1…', why: '「很喜歡」要說 really like / like … very much，very 不能直接修飾動詞。' },
  { re: /\bi am agree\b/i, say: 'I agree', why: 'agree 是動詞，不需要 be 動詞。' },
  { re: /\bdiscuss about\b/i, say: 'discuss', why: 'discuss 後面直接接受詞，不加 about。' },
  { re: /\bmore (better|easier|cheaper|faster)\b/i, say: '$1', why: '比較級不要重複，better 本身就是比較級。' },
  { re: /\bi have (\d+) years? old\b/i, say: 'I am $1 years old', why: '年齡用 be 動詞：I am 25 (years old)。' },
  { re: /\b(he|she|it) (don't|have|are)\b/i, say: '$1 doesn\'t / has / is', why: '第三人稱單數：don\'t → doesn\'t；have → has；are → is。' },
  { re: /\bpeople is\b/i, say: 'people are', why: 'people 是複數名詞。' },
  { re: /\bevery ?day i\b/i, say: 'I … every day', why: 'every day（副詞片語）通常放句尾，或用 Every day, I…。' },
  { re: /\bmake (me|him|her|them) (to) /i, say: 'make $1 + 原形動詞', why: 'make 使役動詞後面接原形動詞，不加 to。' },
  { re: /\bhow to say\b.*\?$/i, say: 'How do you say … in English?', why: '問「怎麼說」的標準句型是 How do you say…？' },
];

TF.LEVELS = [
  { id: 'A2', zh: '初級', xp: 0 }, { id: 'B1', zh: '中級', xp: 300 },
  { id: 'B2', zh: '中高級', xp: 800 }, { id: 'C1', zh: '高級', xp: 1600 }, { id: 'C2', zh: '精通', xp: 3000 },
];

TF.getScenario = (id) => TF.SCENARIOS.find((s) => s.id === id);
